## localhost
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_instituto
spring.datasource.username=postgres
spring.datasource.password=postgres
mercadopago.access-token=APP_USR-5784275331642654-061801-0173a4430edf56cbda9bf187e2e87c29-3482485190
